# Generated by Django 4.2.16 on 2024-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spack', '0003_alter_user_pack_alter_user_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.IntegerField(blank=True, choices=[('499', 'basic'), ('599', 'premium'), ('699', 'vip-premium')], null=True),
        ),
    ]
