# Generated by Django 4.2.16 on 2024-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spack', '0005_alter_user_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
