# Generated by Django 4.2.16 on 2024-10-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spack', '0007_alter_user_price_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
