# Generated by Django 4.2.16 on 2024-10-30 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spack', '0009_alter_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
